#!/bin/bash
# -*- coding: utf-8 -*-
#
#  aptupdate
#  
#  Copyright 2018 Thomas Castleman <draugeros@gmail.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
version="0.0.7-alpha3"
if [ "$1" == "--version" ]; then
  echo -e "\n$version\n"
  exit 0
fi
echo -e "\nUpdating installed software . . . \n"
#updating apt cache then updating install apt packages
if [[ ! -f /etc/mrai/apt-fast.flag ]]; then
  apt update && apt upgrade && apt full-upgrade
  echo -e "\nRemoving old dependencies . . . \n"
  #removing unneeded dependencies
  apt autoremove
  echo -e "\nCleaning up . . . \n"
  #cleaning up
  apt-get clean
  apt purge $(dpkg -l | grep '^rc' | awk '{print $2}')
  #proceed to update snaps, if mrai said to
else
  apt-fast update && apt-fast upgrade && apt-fast dist-upgrade
  echo -e "\nRemoving old dependencies . . . \n"
  #removing unneeded dependencies
  apt-fast autoremove
  echo -e "\nCleaning up . . . \n"
  #cleaning up
  apt-fast clean
  apt-fast purge $(dpkg -l | grep '^rc' | awk '{print $2}')
  #proceed to update snaps, if mrai said to
fi
if [ "$1" == "-s" ]; then
  pkexec /bin/snapupdate
fi
