#!/bin/bash
# -*- coding: utf-8 -*-
#
#  snapupdate
#  
#  Copyright 2018 Thomas Castleman <draugeros@gmail.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
version="0.0.3-alpha2"
if [ "$1" == "--version" ]; then
  echo -e "\n$version\n"
  exit 0
fi
#check for /etc/mrai/snapd.flag
if [ -f /etc/mrai/snapd.flag ]; then
  #force snaps to update
  echo -e "\nForce Updating Snaps. Please Wait . . .\n"
  snap refresh
else
  exit 1
fi
