#!/bin/bash
# -*- coding: utf-8 -*-
#
#  snapupdate
#  
#  Copyright 2019 Thomas Castleman <contact@draugeros.org>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
version="0.1.2-beta2"
scripts="/usr/share/mrai"
called_as="$0"
R='\033[0;31m'
G='\033[0;32m'
NC='\033[0m'
#report errors
error_report () {
	/bin/echo -e "\n$R \bERROR:$NC $2\n"
	"$scripts"/log-out "$1" "/sbin/snapupdate" "$2" "mrai" "$PWD" "$called_as"
	if [[ "$1" != "1" ]]; then
		exit "$1"
	fi
}
if [ "$1" == "--version" ]; then
	/bin/echo -e "\n$version\n"
	exit 0
fi
#check for /etc/mrai/snapd.flag
if [ -f /etc/mrai/snapd.flag ]; then
	#force snaps to update
	/bin/echo -e "\n$G \bForce Updating Snaps. Please Wait . . .$NC\n"
	{
		/usr/bin/snap refresh &
		PID="$!"
		/usr/share/mrai/base-spinner.sh "Updating Snaps . . . " "$PID" && /bin/echo -e "\n"
	} || {
		error_report "$?" "Snap has had an error. Most likely network issues."
	}
	/bin/echo ""
else
	/bin/echo -e "\n$R \bWe're sorry. It appears snapd is not installed. Please run { mrai -ia snapd } to install it.\n"
	exit 1
fi
