#!/bin/sh
cache="/etc/mrai"
/bin/mkdir -p "$cache"
if [ ! -d $cache ]; then
	/bin/mkdir $cache
fi
if [ ! -d $cache/gitauto ]; then
	/bin/mkdir $cache/gitauto
fi
if [ ! -d $cache/gitman ]; then
	/bin/mkdir $cache/gitman
fi
usr=$(users)
if [ -f /home/$usr/.selected_editor ]; then
	/bin/cp /home/$usr/.selected_editor $cache/selected_editor.conf
fi
/bin/chown -R $(users):$(users) $cache
